In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# Intro
learnpytorch.io
pytorch website
matrixmultiplication.xyz
timdettmer
google machine learning handbook
state of the art website

## Ml basics
Google machine learning handbook
What is ml good for
- If you can capture the system with simple rules / other ai, do that instead of ml
- when you have large datasets
-  when the environment constantly changes
What is ml not good for
- explainability
- when a traditional approach is the better option
- when errors are unacceptable
- when there is not much data
Machine learning is good for structured data (xgboost)
- random forest
- gradient boosted models
- naive bayes
- nearest neighbor
- support vector machine
deep learning is good for unstructured data

## Neural networks
### what are they
- encode input data into numbers
- create structure
- get output
- input layer, hidden layer, output layer
### types of learning
- supervised learning
- unsup learning
- self sup learning
- transfer learning

## Pytorch
- deep learning framework
- in python
- able to access prebuilt deep learning models
- whole stack environment 
- mind spore and browse state of the art

### PyTorch workflow
1. Encode data into tensors
2. build / pick a model
3. fit model to data
4. eval model
5. imporve model
6. save and reload your trained model

## Tensors
- fundemental building block of pytorch
- dimensions are the number of square brackets encasing the data
- shape is the count of the different units in each dim
-   shape is the attribute, size() is the function
- scalar and vec = single lowercase letter
- matrix and tensor = single uppercase letter
- By convention, datatype should lead the variable name
- Contain dim, shape, dtype, device and requires_grad variables
- most common errors are wrong datatype, device or shape
- 
### scalar
- scalar = torch.tensor(7)
- This is a single number, and therefore has zero dimensions, its just a scalar
- ndim = 0, size = 1

### Vector
- vec = torch.tensor([1, 2, 3])
- ndim = 1, size = 3

### Matrix
- matrix = torch.tensor([[1, 2], [2, 3]])
- ndim = 2, size = [2, 2]

### TENSPR
- tens = torch.tensor([[[1, 2, 3], [4,5,6], [7,8,9]]])
- ndim = 3, size = [1, 3, 3]

### Creating random tensors
- random tensors are important because initial values in nn are typically random

### zeros and ones
- useful for creating masks
- zeros = torch.zeros(shape)
- multiplying tensor dimensions by zeros or ones manipulates data
- the tensors work in a similar way to numpy in this regard

### torch.arange
- creates a range of numbers like numpy

### tensors like
- copying the shape of other tensors
- new_tensor = torch.zeros_like(input=old_tensor)

### dtype
- the datatype of the tensors
- very common error
- tensor.type() easy way to create a copy

### Tensor operations
- basic operations work element by element
- as in division , multi, add and sub
- both python operators are overloaded and library functions torch.add()
- matrix multiplication
-   aka dot product
-   uses torch.matmul() or torch.mm() or @
- always use torchversion for efficiency sake
- matrix operaations can create shape errors
-   inner dimensions must match
-   (3, 2) * (3, 2) will not work inner does not match
-   (3, 2) * (2, 3) will work, as inner dimesnion does match
-   the resulting matrix has the shape of the outer dimensions combined
-   Shape can be manipulated with transpose, which switches the dimesions 
-   Transpose = tensor.T

### Tensor aggregation
- finding the min max mean sum and other statistics
- as simple as tensor.sum()
- how about positional statistics
-   what is the index of the max
-   tensor.argmax()

### Shaping, stacking, squeezing and unsqueezing
- reshaping - reshapes an input tensor to a defined shape
- view - returns a view of a tensor without changing memory
- stack - combine multiple tensors on each other
- squeeze - removes all 1 dimesnions from a tensor
- unsqueeze - add a 1 dimension to a target tensor
- permutate - permutate a tensor

In [ ]:
RT = torch.rand(2, 2, 2)
RT

In [ ]:
# Create random tensor similar to an image
rand_image_tensor = torch.rand(size=(224, 224, 3))
rand_image_tensor

In [11]:
# tensor shape manipulations
# has to be a factor of the total element size of the tensor
x = torch.arange(1., 10.)
print(x)
print(x.shape)
x_reshape = x.reshape([1, 9])
x_reshape.shape

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.Size([9])


torch.Size([1, 9])

In [12]:
# if youre using view, if you change the underlying data, that change will be relfected on the view
# the view itself cannot be chaged
z = x.view(3, 3)
z, z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [15]:
x_stack = torch.stack([x, x, x], dim=1)
x_stack

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])

In [16]:
x_stack_2 = torch.stack([x,x,x])
x_stack_2

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [34]:
print(x_reshape)
print(x_reshape.squeeze())
print(x_reshape.unsqueeze(dim=-1))  # unsqueeze goes from the outside in, so dim=2 unsqueezes the scalars
# a negative dim goes in the opposite direction, from last dim to newest
# dim reads the shape of the tensor, left to right or right to left, left being the most encapuslating dimension

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([[[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]])


In [36]:
# Permute changes the permutation of the shape of tensor
y = torch.rand(1, 2, 3)
y_permute = y.permute(2, 0, 1)
y.shape, y_permute.shape

(torch.Size([1, 2, 3]), torch.Size([3, 1, 2]))

In [40]:
# indexing with pytorch is similar to indexing with numpy
x = torch.arange(1, 10).reshape(1, 3, 3)
x,  x[0], x[0, 0], x[0, 2, 2],

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(9))

In [45]:
# semicolon selects the entire dimension
# first gets whole tensor, next gets whole tensor again, last grabs the zeroeth column
x[:, :, 0], x[:, 1, :]

(tensor([[1, 4, 7]]), tensor([[4, 5, 6]]))

pytorch and numpy

torch.from_numpy(ndarray)
numpys default dtype is float64, must change for torch

Reproducability, taking the random out of random
to reduce randomness, use seeds

torch.manual_seed(SEED)
torch.rand(shape)

for using gpu
check if cuda is available
count number of devices
device agnostic code doc on pytorch

In [47]:
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor = torch.tensor([1, 2, 3])
tensor.to(device)
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [48]:
# moving tensor back to cpu
tensor.cpu().device

device(type='cpu')